name: Release

on:
  push:
    tags:
    - v*.*.*

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Build
      run: |
        make build-all
        make build-archive

    - name: Release
      uses: softprops/action-gh-release@67b6c38432c171b8aa64dc6f3f152d12da2d99fa
      with:
        files: dist/*.tar.gz
